import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  skeletonStack: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  summary: {
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    margin: 0,
  } satisfies CSSProperties,
  caveat: {
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    border: "1px solid var(--warn)",
    borderRadius: 8,
    padding: "9px 11px",
    background: "color-mix(in srgb, var(--warn) 8%, transparent)",
  } satisfies CSSProperties,
  depthCaveat: {
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.5,
    margin: 0,
  } satisfies CSSProperties,
  statRow: {
    display: "flex",
    alignItems: "center",
    gap: 22,
    flexWrap: "wrap",
    padding: "2px 0 4px",
  } satisfies CSSProperties,
  stat: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
  } satisfies CSSProperties,
  statIcon: {
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  statValue: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 13.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tree: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  symbolRow: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  symbolHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "10px 12px",
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  symbolName: {
    fontSize: 13.5,
    fontWeight: 700,
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
  symbolIcon: {
    color: "var(--accent-text)",
    flexShrink: 0,
  } satisfies CSSProperties,
  symbolCounts: {
    marginLeft: "auto",
    fontSize: 12,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  symbolBody: {
    padding: "8px 12px 12px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  /* Callers render as a flat list with a tree-branch rail (border-left) and a
     ↳ glyph per row — no per-file grouping, no caller-fn name (the file:line
     link is the whole row). Matches the reference. */
  callerList: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    marginLeft: 7,
    paddingLeft: 12,
    borderLeft: "1px solid var(--border)",
  } satisfies CSSProperties,
  callerRow: {
    display: "flex",
    alignItems: "center",
    gap: 7,
  } satisfies CSSProperties,
  callerArrow: {
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  truncationNote: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    marginLeft: 7,
    paddingLeft: 12,
  } satisfies CSSProperties,
  impactTags: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginLeft: 7,
    paddingLeft: 12,
  } satisfies CSSProperties,
  endpointTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 9px",
    borderRadius: 6,
    fontSize: 12,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  endpointMethod: {
    fontWeight: 700,
  } satisfies CSSProperties,
  cronTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 9px",
    borderRadius: 6,
    fontSize: 12,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--warn)",
    background: "var(--warn-bg)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  plainRef: {
    fontSize: 13,
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
} as const;
