import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillTab. */
export const s = {
  fileInput: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  error: {
    marginTop: 10,
    fontSize: 13,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    border: "1px solid var(--crit)",
    borderRadius: 7,
    padding: "8px 12px",
  } satisfies CSSProperties,
  pending: { fontSize: 13, color: "var(--text-muted)", marginTop: 10 } satisfies CSSProperties,
  preview: { marginTop: 22, borderTop: "1px solid var(--border)", paddingTop: 20 } satisfies CSSProperties,
  previewHint: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    lineHeight: 1.5,
    margin: "-6px 0 16px",
  } satisfies CSSProperties,
  notice: {
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    background: "var(--warn-bg)",
    border: "1px solid var(--warn)",
    borderRadius: 8,
    padding: "10px 12px",
    marginBottom: 18,
  } satisfies CSSProperties,
  noticeIcon: { color: "var(--warn)", flexShrink: 0, marginTop: 1 } satisfies CSSProperties,
  body: {
    maxHeight: 260,
    overflow: "auto",
    margin: 0,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-primary)",
    color: "var(--text-secondary)",
    fontSize: 12.5,
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  block: { marginBottom: 18 } satisfies CSSProperties,
  blockHint: {
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.5,
    margin: "-8px 0 10px",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    gap: 10,
    alignItems: "baseline",
    fontSize: 12.5,
    padding: "5px 0",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  rowPath: { color: "var(--text-primary)", flex: 1, wordBreak: "break-all" } satisfies CSSProperties,
  rowReason: { color: "var(--text-muted)" } satisfies CSSProperties,
  warning: {
    fontSize: 12.5,
    color: "var(--warn)",
    lineHeight: 1.5,
    padding: "3px 0",
  } satisfies CSSProperties,
  actions: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
} as const;
